### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by albertmena**
When` scipion3 installp -p scipion-em-xmipptomo` and open a project: 

```
 error when importing from xmipptomo.protocols: No module named 'imod'
   File "/home/xmippuser/scipion3/software/em/scipion-em-xmipptomo/xmipptomo/protocols/protocol_dose_filter.py", line 28, in <module>

```
Installing scipion-em-imod it does not happen
Not sure if that requirements is to heavy

### CODE REVIEW

**Comment by fede-pe** [comment]
I have installed scipion-em-xmipptomo without imod and I have come across with no errors.

**Comment by albertmena** [comment]
> I have installed scipion-em-xmipptomo without imod and I have come across with no errors.

but could you run the test also?

**Comment by fede-pe** [comment]
> 

You were right, the tests were not passing. I think the problem was some unused imports. I have removed them and now these tests are passing. Nonetheless, there are still some tests failing but nothing related to imod. Please check if it behaves samely in your machine.

**Comment by Vilax** [comment]
My bad the imod import, sorry

I agree there are some unused imports. Thanks for checking Alberto

**Comment by Vilax** [comment]
And Fede for fix the others

**Review by Vilax — APPROVED** [review]

**Comment by albertmena** [comment]
Nice!,

**Pull request merged**
