### PR TITLE
adding FlexAlign for tilt series alignment

### PR DESCRIPTION
**Pull request by DStrelak**
This requires both Xmipp and Scipion-em-Xmipp to be present. May I assume that this is true? @pconesa  @JorMaister

### CODE REVIEW

**Comment by pconesa** [comment]
yep, most probably both will be there.

**Comment by EstrellaFG** [comment]
Actually, scipion-em-xmipp is a requirement for this plugin.

**Comment by pconesa** [comment]
Trigger by cryoCARE integration....we are going to need to output tiltseries from odd and even frames.....
Is this something FlexAlign has implemented or can easily do

**Comment by DStrelak** [comment]
> Trigger by cryoCARE integration....we are going to need to output tiltseries from odd and even frames.....

No. We currently support only sub-range of the frames. But I guess it would not be too hard to implement.
I am a bit worried about the precision though. There are not so many frames in the tiltserie movie (typically around 10, I think), and using just half of them might not be enough to get decent results. Simple averaging might be better in this case.
@cossorzano , what do you think?

**Comment by pconesa** [comment]
The even odd stuff is to get a noise signal model for a denoiser so it might no be relevant if results are not ideal.

**Comment by cossorzano** [comment]
Even, odd stuff should have been already integrated by Federico. It must be in one of his branches.

**Comment by pconesa** [comment]
Yes but that is for tilt series, we want this for tilt series movies

**Comment by pconesa** [comment]
Nevermind .... I think this is out of the scope of this PR.

**Comment by pconesa** [comment]
Actually, I think we want:

1.- align a movie + output stack (this is already implemented)
2.- split odd /even
3.- sum: full stack, odd stack, even stack

**Comment by fede-pe** [comment]
Even though this PR has been closed just a couple of points I would like to bring up:

- About the odd-even splitting stuff, now it is only implemented for tilt-series (no tilt-series movies as @pconesa said). I am not aware of any protocol to sum stacks/frames.

- @DStrelak, I have tried to run protocol with the dataset 10164 from Empiar. I have obtained this error:

00031:   Exception: Expected output file 'Runs/000354_XmippProtTsFlexAlign/extra/TS_00.mrc' not produced!

That output file is not generated (actually it looks like it is generated in the tmp folder). I guess it is due to some outdated repository / wrong branch, but it would be helpful if you cloud help me troubleshooting.

**Pull request merged**
